### PR TITLE
Compute network magnitudes

### LINKED ISSUE #103: Network Magnitudes
It would be useful to get  network magnitudes for each detection. 
Then during the post-processing with `scolv` we can screen magnitudes easily.

### PR DESCRIPTION
**Pull request by damb**
Compute [network magnitudes](https://docs.gempa.de/seiscomp/current/apps/scmag.html#network-magnitudes) as the median of the corresponding station magnitudes.

Closes #103.

### CODE REVIEW

**Comment by damb** [comment]
@mmesim, please check on your side whether both station magnitudes and network magnitudes can be displayed in `scolv`.

**Comment by mmesim** [comment]
@luca-s 
Network Magnitudes are ok
Network Magnitudes


Still cannot see Station Magnitudes
Screenshot from 2022-05-12 10-17-16

**Comment by damb** [comment]
@luca-s, do you know which prerequisites need to be fulfilled in order to display station magnitudes?

**Comment by damb** [comment]
Ok. Got it.

In order to display `DataModel::StationMagnitude`s in `scolv` the `WaveformID` needs to be set.

**Comment by damb** [comment]
@mmesim, could you please check once again on your side?

**Comment by mmesim** [comment]
Still no station magnitudes.

**Comment by luca-s** [comment]
@mmesim could you domp the origin in SCXL so we can see what is missing?

**Comment by mmesim** [comment]
@damb Great job! It works!
@luca-s Thanks a lot for your help!! 
:tada: :tada: :tada: :tada: :tada: :tada: :tada: 

Screenshot from 2022-05-16 17-24-21

**Pull request merged**
