### PR TITLE
Refactor detector; fix trigger facilities

### LINKED ISSUE #62: Multi-channel detections
[14.test.zip](https://github.com/damb/scdetect/files/7556876/14.test.zip)

The zip file includes the the files I used to run #14.test. The test uses one earthquake as template and the S-phase on the two horizontal components of the same station. It returns 6 detections. However, when the `scdetect` is applied on each channel separately I get 122, for the HHE, and 90 for the HHN. To my understanding the number of detections should be 90 or a little bit less than that. 

**Note:** I did not use the attribute `arrivalOffsetThreshold`. It might be a good opportunity to explore that, i.e how should we tune the `arrivalOffsetThreshold` to get the right number of detections .

### PR DESCRIPTION
**Pull request by damb**
**Bugfixes**:
- Fix trigger facilities; switch to pick time based triggering (similar to the implementation provided by `scautopick`)

**Features and Changes**:
- Refactor detector facilities

Closes #62, #66.

### CODE REVIEW

**Comment by damb** [comment]
@mmesim, as suspected the trigger implementation required a fix. I througly checked against the data provided from both #62 and #66. Could you check on your side as well?

**Comment by damb** [comment]
Note that besides of the origin time issue described, the number of detections is affected, too.

**Comment by mmesim** [comment]
@damb Ok, will try to check it by Thursday, the latest (this week :D).

**Review by mmesim — APPROVED** [review]
It seems like a nice code! 

Well, I closed #62 and #66. It works well now and the results make sense. 

You did a great job @damb. I'm very happy that you solved this. 

cheers to the next bug!

**Comment by damb** [comment]
Thanks @mmesim. I'm going to merge.

**Comment by mmesim** [comment]
@damp This is a good idea. The data I used are 1hr long. However, I can create a small chunk (~60 sec) and provide you with all the files necessary for the tests.

**Comment by damb** [comment]
Sounds good. The metadata is already available from both #62 and #66.

**Comment by damb** [comment]
Note that this PR requires a follow-up. See #87.

**Pull request merged**
